// <auto-generated />
namespace Prova_UCDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class desconto_percentual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(desconto_percentual));
        
        string IMigrationMetadata.Id
        {
            get { return "202202050542166_desconto_percentual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
